# Generated by Django 5.0.6 on 2024-06-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('names', models.CharField(max_length=255)),
                ('lastnames', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
