# Generated by Django 5.0.6 on 2024-06-09 22:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=1)),
                ('capacity', models.PositiveIntegerField()),
                ('year', models.IntegerField(editable=False)),
                ('semester', models.IntegerField(editable=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='WorkloadLab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=1)),
                ('capacity', models.PositiveIntegerField()),
                ('year', models.IntegerField(editable=False)),
                ('semester', models.IntegerField(editable=False)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.laboratory')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
    ]
