# Generated by Django 5.0.6 on 2024-06-09 22:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('workloads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('workload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workloads.workload')),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionLab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('workload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workloads.workloadlab')),
            ],
        ),
    ]
